language: cpp
compiler:
 - clang
 - gcc
dist: trusty
sudo: required
os:
- linux
matrix:
 include:
  - env: TARGET_OS=win32
  - env: TARGET_OS=win64
  - env: TARGET_OS=linux
  - env: QT5=True TARGET_OS=linux
install:
 - . ${TRAVIS_BUILD_DIR}/.travis/${TRAVIS_OS_NAME}.${TARGET_OS}.install.sh
script:
 - qmake stereograma.pro
 - make -j4
